<?php

namespace AppBundle\Repository;

/**
 * BusJourneyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusJourneyRepository extends \Doctrine\ORM\EntityRepository
{
}
