<?php

namespace AppBundle\Repository;

/**
 * BusStopStudentDefaultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusStopStudentDefaultRepository extends \Doctrine\ORM\EntityRepository
{
}
