<?php

namespace AppBundle\Repository;

/**
 * BusStopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusStopRepository extends \Doctrine\ORM\EntityRepository
{
}
